
DEFINE TEMP-TABLE ttCustomer NO-UNDO SERIALIZE-NAME "Account"
  FIELD id       AS CHARACTER FORMAT "x(20)"
  FIELD custType AS CHARACTER SERIALIZE-NAME "Type"
  FIELD custName AS CHARACTER SERIALIZE-NAME "Name"
  INDEX idxMain id.